const { Transaction, TransactionAudit, sequelize } = require("../models");
// CHANGED: USERID TO PLAYERID
async function seedTransactions() {
  await sequelize.authenticate();

  // Remove old data (optional, for clean seed)
  await TransactionAudit.destroy({ where: {} });
  await Transaction.destroy({ where: {} });

  // Seed transactions with various types, amounts, currencies, users, vendors, games, and dates
  const transactions = [
    // Bets
    {
      externalTransactionId: "EXT123456",
      provider: "zenith",
      type: "bet",
      amount: 100.5,
      currency: "USD",
      status: "success",
      playerId: 1,
      clientId: 1,
      agentId: 1,
      gameId: 1,
      vendorId: 1,
      roundId: "ROUND789",
      balanceBefore: 1000,
      balanceAfter: 899.5,
      metadata: { game: "slots", platform: "web" },
      created_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000), // 6 days ago
    },
    {
      externalTransactionId: "EXT123457",
      provider: "zenith",
      type: "bet",
      amount: 200,
      currency: "USD",
      status: "success",
      playerId: 2,
      clientId: 2,
      agentId: 2,
      gameId: 2,
      vendorId: 2,
      roundId: "ROUND790",
      balanceBefore: 1500,
      balanceAfter: 1300,
      metadata: { game: "roulette", platform: "mobile" },
      created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000), // 5 days ago
    },
    {
      externalTransactionId: "EXT123458",
      provider: "zenith",
      type: "bet",
      amount: 150,
      currency: "EUR",
      status: "success",
      playerId: 3,
      clientId: 1,
      agentId: 1,
      gameId: 3,
      vendorId: 1,
      roundId: "ROUND791",
      balanceBefore: 800,
      balanceAfter: 650,
      metadata: { game: "blackjack", platform: "web" },
      created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000), // 4 days ago
    },
    // Wins
    {
      externalTransactionId: "EXT123459",
      provider: "zenith",
      type: "win",
      amount: 50,
      currency: "USD",
      status: "success",
      playerId: 1,
      clientId: 1,
      agentId: 1,
      gameId: 1,
      vendorId: 1,
      roundId: "ROUND789",
      balanceBefore: 899.5,
      balanceAfter: 949.5,
      metadata: { game: "slots", platform: "web" },
      created_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
    },
    {
      externalTransactionId: "EXT123460",
      provider: "zenith",
      type: "win",
      amount: 80,
      currency: "USD",
      status: "success",
      playerId: 2,
      clientId: 2,
      agentId: 2,
      gameId: 2,
      vendorId: 2,
      roundId: "ROUND790",
      balanceBefore: 1300,
      balanceAfter: 1380,
      metadata: { game: "roulette", platform: "mobile" },
      created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    },
    {
      externalTransactionId: "EXT123461",
      provider: "zenith",
      type: "win",
      amount: 60,
      currency: "EUR",
      status: "success",
      playerId: 3,
      clientId: 1,
      agentId: 1,
      gameId: 3,
      vendorId: 1,
      roundId: "ROUND791",
      balanceBefore: 650,
      balanceAfter: 710,
      metadata: { game: "blackjack", platform: "web" },
      created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    },
    // Rollbacks
    {
      externalTransactionId: "EXT123462",
      provider: "zenith",
      type: "rollback",
      amount: 10,
      currency: "USD",
      status: "success",
      playerId: 1,
      clientId: 1,
      agentId: 1,
      gameId: 1,
      vendorId: 1,
      roundId: "ROUND789",
      balanceBefore: 949.5,
      balanceAfter: 959.5,
      metadata: { game: "slots", platform: "web" },
      created_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
    },
    {
      externalTransactionId: "EXT123463",
      provider: "zenith",
      type: "rollback",
      amount: 20,
      currency: "USD",
      status: "success",
      playerId: 2,
      clientId: 2,
      agentId: 2,
      gameId: 2,
      vendorId: 2,
      roundId: "ROUND790",
      balanceBefore: 1380,
      balanceAfter: 1400,
      metadata: { game: "roulette", platform: "mobile" },
      created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    },
    {
      externalTransactionId: "EXT123464",
      provider: "zenith",
      type: "rollback",
      amount: 15,
      currency: "EUR",
      status: "success",
      playerId: 3,
      clientId: 1,
      agentId: 1,
      gameId: 3,
      vendorId: 1,
      roundId: "ROUND791",
      balanceBefore: 710,
      balanceAfter: 725,
      metadata: { game: "blackjack", platform: "web" },
      created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    },
    // More variety for today
    {
      externalTransactionId: "EXT123465",
      provider: "zenith",
      type: "bet",
      amount: 300,
      currency: "USD",
      status: "success",
      playerId: 4,
      clientId: 2,
      agentId: 2,
      gameId: 4,
      vendorId: 2,
      roundId: "ROUND792",
      balanceBefore: 2000,
      balanceAfter: 1700,
      metadata: { game: "poker", platform: "web" },
      created_at: new Date(),
    },
    {
      externalTransactionId: "EXT123466",
      provider: "zenith",
      type: "win",
      amount: 120,
      currency: "USD",
      status: "success",
      playerId: 4,
      clientId: 2,
      agentId: 2,
      gameId: 4,
      vendorId: 2,
      roundId: "ROUND792",
      balanceBefore: 1700,
      balanceAfter: 1820,
      metadata: { game: "poker", platform: "web" },
      created_at: new Date(),
    },
    {
      externalTransactionId: "EXT123467",
      provider: "zenith",
      type: "rollback",
      amount: 30,
      currency: "USD",
      status: "success",
      playerId: 4,
      clientId: 2,
      agentId: 2,
      gameId: 4,
      vendorId: 2,
      roundId: "ROUND792",
      balanceBefore: 1820,
      balanceAfter: 1850,
      metadata: { game: "poker", platform: "web" },
      created_at: new Date(),
    },
  ];

  for (const trx of transactions) {
    const transaction = await Transaction.create(trx);

    await TransactionAudit.create({
      transactionId: transaction.id,
      clientId: transaction.clientId,
      agentId: transaction.agentId,
      gameId: transaction.gameId,
      vendorId: transaction.vendorId,
      aggregatorName: "zenith",
      rawPayload: {
        original: "payload from upstream",
        details: { some: "data" },
      },
      receivedAt: transaction.created_at || new Date(),
    });
  }

  console.log("Seeded multiple Transactions and TransactionAudits.");
}

module.exports = seedTransactions;
